version: '3'
services: 
  app:
    container_name: menu-module
    restart: always
    build: .
    ports:
      - '80:3005'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
